name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
    - name: Log in to Docker Hub
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: .
        push: true
        tags: moderras/miaostaycdn:latest
    - name: Deploy to Server
      uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
      with:
        # ssh remote host
        host: ${{ secrets.SERVER_IP }}
        # ssh remote port
        port: ${{ secrets.SERVER_PORT }}
        # ssh remote user
        user: ${{ secrets.SERVER_USER }}
        # ssh remote password
        pass: ${{ secrets.SERVER_PASSWORD }}
        # execute pre-commands before scp
        first_ssh: kubectl delete pods typecho && kubectl apply -f /data/typecho/typecho.yaml
  
